name: "Add comment if all assignees have commented"
on:
  issue_comment:
    types:
      - created
jobs:
  primary:
  if: ${{ !github.event.issue.pull_request }}
  runs-on: ubuntu—latest
  steps:
  - name: Checkout repo
    uses: actions/checkout@v2 

  - name: Notify if all assignees have commented 
    uses: mvkaran/comment-on-issue@v1.0
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LABEL: 'weekly—update'
      COMMENT: 'Looks I ike everyone has shared their inputs for the weekly update!'
