name: "Agregue un comentario si todos los asignados han comentado"
on:
  issue_comment:
    types:
      - created
jobs:
  primary:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2 

    - name: Notificar si todos los asignados han comentado
      #uses: IESAlisal/DevOpsK8s_GitHub_Actions@v1.0
      uses: mvkaran/comment-on-issue@v1.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Esta etiqueta es obligatoria para que la accion funcione!!!!!!!!!!!!
        LABEL: 'Actualización semanal'
        COMMENT: 'Parece que todos han compartido sus aportaciones para la actualización semanal. ¡Genial!'
